Armor.create!([
  {name: "Ancient Helm", location: nil, cost: 2000},
  {name: "Ancient Cuirass", location: nil, cost: 2000},
  {name: "Ancient Greaves", location: nil, cost: 2000},
  {name: "Barbarian Helm", location: nil, cost: 2000},
  {name: "Barbarian Armor", location: nil, cost: 2000},
  {name: "Barbarian Leg", location: nil, cost: 2000}
])
ArmorPiece.create!([
  {armor_id: 1, level: 1, player_id: 1},
  {armor_id: 2, level: 1, player_id: 1},
  {armor_id: 3, level: 1, player_id: 1},
  {armor_id: 6, level: 1, player_id: 1}
])
Item.create!([
  {name: "Ancient Screw"},
  {name: "Ancient Spring"},
  {name: "Ancient Gear"},
  {name: "Ancient Shaft"},
  {name: "Ancient Core"},
  {name: "Giant Ancient Core"},
  {name: "Star Fragment"},
  {name: "Lynel Horn"},
  {name: "Lynel Hoof"},
  {name: "Lynel Guts"},
  {name: "Shard of Dinraal's Horn"}
])
Level.create!([
  {armor_id: 1, level: 1},
  {armor_id: 1, level: 2},
  {armor_id: 1, level: 3},
  {armor_id: 1, level: 4},
  {armor_id: 2, level: 1},
  {armor_id: 2, level: 2},
  {armor_id: 2, level: 3},
  {armor_id: 2, level: 4},
  {armor_id: 3, level: 1},
  {armor_id: 3, level: 2},
  {armor_id: 3, level: 3},
  {armor_id: 3, level: 4},
  {armor_id: 4, level: 1},
  {armor_id: 4, level: 2},
  {armor_id: 4, level: 3},
  {armor_id: 4, level: 4},
  {armor_id: 5, level: 1},
  {armor_id: 5, level: 2},
  {armor_id: 5, level: 3},
  {armor_id: 5, level: 4},
  {armor_id: 6, level: 1},
  {armor_id: 6, level: 2},
  {armor_id: 6, level: 3},
  {armor_id: 6, level: 4}
])
LevelUpItem.create!([
  {level_id: 1, item_id: 1, count: 5},
  {level_id: 1, item_id: 2, count: 5},
  {level_id: 2, item_id: 2, count: 15},
  {level_id: 2, item_id: 3, count: 10},
  {level_id: 3, item_id: 4, count: 15},
  {level_id: 3, item_id: 5, count: 5},
  {level_id: 4, item_id: 6, count: 2},
  {level_id: 4, item_id: 7, count: 1},
  {level_id: 5, item_id: 1, count: 5},
  {level_id: 5, item_id: 2, count: 5},
  {level_id: 6, item_id: 2, count: 15},
  {level_id: 6, item_id: 3, count: 10},
  {level_id: 7, item_id: 4, count: 15},
  {level_id: 7, item_id: 5, count: 5},
  {level_id: 8, item_id: 6, count: 2},
  {level_id: 8, item_id: 7, count: 1},
  {level_id: 9, item_id: 1, count: 5},
  {level_id: 9, item_id: 2, count: 5},
  {level_id: 10, item_id: 2, count: 15},
  {level_id: 10, item_id: 3, count: 10},
  {level_id: 11, item_id: 4, count: 15},
  {level_id: 11, item_id: 5, count: 5},
  {level_id: 12, item_id: 6, count: 2},
  {level_id: 12, item_id: 7, count: 1},
  {level_id: 14, item_id: 8, count: 3},
  {level_id: 14, item_id: 9, count: 2},
  {level_id: 15, item_id: 9, count: 4},
  {level_id: 15, item_id: 10, count: 1},
  {level_id: 16, item_id: 10, count: 2},
  {level_id: 16, item_id: 11, count: 1},
  {level_id: 17, item_id: 8, count: 1},
  {level_id: 18, item_id: 8, count: 3},
  {level_id: 18, item_id: 9, count: 2},
  {level_id: 19, item_id: 9, count: 4},
  {level_id: 19, item_id: 10, count: 1},
  {level_id: 20, item_id: 10, count: 2},
  {level_id: 20, item_id: 11, count: 1},
  {level_id: 21, item_id: 8, count: 1},
  {level_id: 22, item_id: 8, count: 3},
  {level_id: 22, item_id: 9, count: 2},
  {level_id: 23, item_id: 9, count: 4},
  {level_id: 23, item_id: 10, count: 1},
  {level_id: 24, item_id: 10, count: 2},
  {level_id: 24, item_id: 11, count: 1}
])
Player.create!([
  {name: "Link"}
])
