Armor.create!([
  {name: "Ancient Helm", location: nil, cost: 2000},
  {name: "Ancient Cuirass", location: nil, cost: 2000},
  {name: "Ancient Greaves", location: nil, cost: 2000},
  {name: "Barbarian Helm", location: nil, cost: 2000},
  {name: "Barbarian Armor", location: nil, cost: 2000},
  {name: "Barbarian Leg Wraps", location: nil, cost: 2000},
  {name: "Climber's Bandana", location: nil, cost: nil},
  {name: "Climbing Gear", location: nil, cost: nil},
  {name: "Climbing Boots", location: nil, cost: nil},
  {name: "Dark Hood", location: nil, cost: nil},
  {name: "Dark Tunic", location: nil, cost: nil},
  {name: "Dark Trousers", location: nil, cost: nil},
  {name: "Desert Voe Headband", location: nil, cost: nil},
  {name: "Desert Voe Spaulder", location: nil, cost: nil},
  {name: "Desert Voe Trousers", location: nil, cost: nil},
  {name: "Flamebreaker Helm", location: nil, cost: nil},
  {name: "Flamebreaker Armor", location: nil, cost: nil},
  {name: "Flamebreaker Boots", location: nil, cost: nil},
  {name: "Gerudo Veil", location: nil, cost: nil},
  {name: "Gerudo Top", location: nil, cost: nil},
  {name: "Gerudo Sirwal", location: nil, cost: nil},
  {name: "Hylian Hood", location: nil, cost: nil},
  {name: "Hylian Tunic", location: nil, cost: nil},
  {name: "Hylian Trousers", location: nil, cost: nil},
  {name: "Radiant Mask", location: nil, cost: nil},
  {name: "Radiant Shirt", location: nil, cost: nil},
  {name: "Radiant Tights", location: nil, cost: nil},
  {name: "Stealth Mask", location: nil, cost: nil},
  {name: "Stealth Chest Guard", location: nil, cost: nil},
  {name: "Stealth Tights", location: nil, cost: nil},
  {name: "Snowquill Headdress", location: nil, cost: nil},
  {name: "Snowquill Tunic", location: nil, cost: nil},
  {name: "Snowquill Trousers", location: nil, cost: nil},
  {name: "Soldier's Helm", location: nil, cost: nil},
  {name: "Soldier's Armor", location: nil, cost: nil},
  {name: "Soldier's Greaves", location: nil, cost: nil},
  {name: "Zora Helm", location: nil, cost: nil},
  {name: "Zora Armor", location: nil, cost: nil},
  {name: "Zora Greaves", location: nil, cost: nil},
  {name: "Cap of the Wild", location: nil, cost: nil},
  {name: "Tunic of the Wild", location: nil, cost: nil},
  {name: "Trousers of the Wild", location: nil, cost: nil},
  {name: "Champion's Tunic", location: nil, cost: nil},
  {name: "Rubber Helm", location: nil, cost: nil},
  {name: "Rubber Armor", location: nil, cost: nil},
  {name: "Rubber Tights", location: nil, cost: nil}
])
ArmorPiece.create!([
  {armor_id: 1, level: 1, player_id: 1},
  {armor_id: 2, level: 1, player_id: 1},
  {armor_id: 3, level: 1, player_id: 1},
  {armor_id: 6, level: 1, player_id: 1},
  {armor_id: 43, level: 1, player_id: 1},
  {armor_id: 22, level: 1, player_id: 1},
  {armor_id: 23, level: 1, player_id: 1},
  {armor_id: 24, level: 1, player_id: 1},
  {armor_id: 31, level: 1, player_id: 1},
  {armor_id: 32, level: 1, player_id: 1},
  {armor_id: 33, level: 1, player_id: 1},
  {armor_id: 13, level: 1, player_id: 1},
  {armor_id: 14, level: 1, player_id: 1},
  {armor_id: 15, level: 1, player_id: 1},
  {armor_id: 19, level: 1, player_id: 1},
  {armor_id: 20, level: 1, player_id: 1},
  {armor_id: 21, level: 1, player_id: 1},
  {armor_id: 7, level: 1, player_id: 1},
  {armor_id: 8, level: 1, player_id: 1},
  {armor_id: 9, level: 1, player_id: 1},
  {armor_id: 16, level: 1, player_id: 1},
  {armor_id: 17, level: 1, player_id: 1},
  {armor_id: 18, level: 1, player_id: 1},
  {armor_id: 27, level: 1, player_id: 1},
  {armor_id: 26, level: 1, player_id: 1},
  {armor_id: 25, level: 1, player_id: 1},
  {armor_id: 28, level: 1, player_id: 1},
  {armor_id: 29, level: 1, player_id: 1},
  {armor_id: 30, level: 1, player_id: 1},
  {armor_id: 38, level: 1, player_id: 1},
  {armor_id: 4, level: 1, player_id: 1},
  {armor_id: 5, level: 1, player_id: 1},
  {armor_id: 45, level: 1, player_id: 1},
  {armor_id: 46, level: 1, player_id: 1},
  {armor_id: 34, level: 1, player_id: 1},
  {armor_id: 35, level: 1, player_id: 1},
  {armor_id: 36, level: 1, player_id: 1},
  {armor_id: 42, level: 1, player_id: 1},
  {armor_id: 41, level: 1, player_id: 1},
  {armor_id: 40, level: 1, player_id: 1}
])
Item.create!([
  {name: "Ancient Screw"},
  {name: "Ancient Spring"},
  {name: "Ancient Gear"},
  {name: "Ancient Shaft"},
  {name: "Ancient Core"},
  {name: "Giant Ancient Core"},
  {name: "Star Fragment"},
  {name: "Lynel Horn"},
  {name: "Lynel Hoof"},
  {name: "Lynel Guts"},
  {name: "Shard of Dinraal's Horn"},
  {name: "Keese Wing"},
  {name: "Rushroom"},
  {name: "Electric Keese Wing"},
  {name: "Hightail Lizard"},
  {name: "Ice Keese Wing"},
  {name: "Hot-Footed Frog"},
  {name: "Fire Keese Wing"},
  {name: "Swift Violet"},
  {name: "White Chuchu Jelly"},
  {name: "Icy Lizalfos Tail"},
  {name: "Sapphire"},
  {name: "Fireproof Lizard"},
  {name: "Moblin Horn"},
  {name: "Moblin Fang"},
  {name: "Smotherwing Butterfly"},
  {name: "Moblin Guts"},
  {name: "Hinox Guts"},
  {name: "Bokoblin Horn"},
  {name: "Bokoblin Fang"},
  {name: "Bokoblin Guts"},
  {name: "Amber"},
  {name: "Luminous Stone"},
  {name: "Molduga Guts"},
  {name: "Yellow Chuchu Jelly"},
  {name: "Voltfruit"},
  {name: "Zapshroom"},
  {name: "Yellow Lizalfos Tail"},
  {name: "Topaz"},
  {name: "Blue Nightshade"},
  {name: "Sunset Firefly"},
  {name: "Silent Shroom"},
  {name: "Sneaky River Snail"},
  {name: "Stealthfin Trout"},
  {name: "Silent Princess"},
  {name: "Red Chuchu Jelly"},
  {name: "Warm Safflina"},
  {name: "Sunshroom"},
  {name: "Red Lizalfos Tail"},
  {name: "Ruby"},
  {name: "Chuchu Jelly"},
  {name: "Keese Eyeball"},
  {name: "Lizalfos Tail"},
  {name: "Lizalfos Horn"},
  {name: "Lizalfos Talon"},
  {name: "Hyrule Bass"},
  {name: "Hearty Bass"},
  {name: "Opal"},
  {name: "Acorn"},
  {name: "Courser Bee Honey"},
  {name: "Energetic Rhino Beetle"},
  {name: "Shard of Farosh's Horn"},
  {name: "Shard of Naydra's Horn"},
  {name: "Dinraal's Scale"},
  {name: "Dinraal's Claw"},
  {name: "Dinraal's Fang"},
  {name: "Farosh's Scale"},
  {name: "Farosh's Claw"},
  {name: "Farosh's Fang"},
  {name: "Naydra's Scale"},
  {name: "Naydra's Claw"},
  {name: "Naydra's Fang"}
])
Level.create!([
  {armor_id: 1, level: 1},
  {armor_id: 1, level: 2},
  {armor_id: 1, level: 3},
  {armor_id: 1, level: 4},
  {armor_id: 2, level: 1},
  {armor_id: 2, level: 2},
  {armor_id: 2, level: 3},
  {armor_id: 2, level: 4},
  {armor_id: 3, level: 1},
  {armor_id: 3, level: 2},
  {armor_id: 3, level: 3},
  {armor_id: 3, level: 4},
  {armor_id: 4, level: 1},
  {armor_id: 4, level: 2},
  {armor_id: 4, level: 3},
  {armor_id: 4, level: 4},
  {armor_id: 5, level: 1},
  {armor_id: 5, level: 2},
  {armor_id: 5, level: 3},
  {armor_id: 5, level: 4},
  {armor_id: 6, level: 1},
  {armor_id: 6, level: 2},
  {armor_id: 6, level: 3},
  {armor_id: 6, level: 4},
  {armor_id: 7, level: 1},
  {armor_id: 7, level: 2},
  {armor_id: 7, level: 3},
  {armor_id: 7, level: 4},
  {armor_id: 8, level: 1},
  {armor_id: 8, level: 2},
  {armor_id: 8, level: 3},
  {armor_id: 8, level: 4},
  {armor_id: 9, level: 1},
  {armor_id: 9, level: 2},
  {armor_id: 9, level: 3},
  {armor_id: 13, level: 1},
  {armor_id: 13, level: 2},
  {armor_id: 13, level: 3},
  {armor_id: 13, level: 4},
  {armor_id: 14, level: 1},
  {armor_id: 14, level: 2},
  {armor_id: 14, level: 3},
  {armor_id: 14, level: 4},
  {armor_id: 15, level: 1},
  {armor_id: 15, level: 2},
  {armor_id: 15, level: 3},
  {armor_id: 15, level: 4},
  {armor_id: 16, level: 1},
  {armor_id: 16, level: 2},
  {armor_id: 16, level: 3},
  {armor_id: 16, level: 4},
  {armor_id: 17, level: 1},
  {armor_id: 17, level: 2},
  {armor_id: 17, level: 3},
  {armor_id: 17, level: 4},
  {armor_id: 18, level: 1},
  {armor_id: 18, level: 2},
  {armor_id: 18, level: 3},
  {armor_id: 18, level: 4},
  {armor_id: 22, level: 1},
  {armor_id: 22, level: 2},
  {armor_id: 22, level: 3},
  {armor_id: 22, level: 4},
  {armor_id: 23, level: 1},
  {armor_id: 23, level: 2},
  {armor_id: 23, level: 3},
  {armor_id: 23, level: 4},
  {armor_id: 24, level: 1},
  {armor_id: 24, level: 2},
  {armor_id: 24, level: 3},
  {armor_id: 24, level: 4},
  {armor_id: 25, level: 1},
  {armor_id: 25, level: 2},
  {armor_id: 25, level: 3},
  {armor_id: 25, level: 4},
  {armor_id: 26, level: 1},
  {armor_id: 26, level: 2},
  {armor_id: 26, level: 3},
  {armor_id: 26, level: 4},
  {armor_id: 27, level: 1},
  {armor_id: 27, level: 2},
  {armor_id: 27, level: 3},
  {armor_id: 27, level: 4},
  {armor_id: 28, level: 1},
  {armor_id: 28, level: 2},
  {armor_id: 28, level: 3},
  {armor_id: 28, level: 4},
  {armor_id: 29, level: 1},
  {armor_id: 29, level: 2},
  {armor_id: 29, level: 3},
  {armor_id: 29, level: 4},
  {armor_id: 30, level: 1},
  {armor_id: 30, level: 2},
  {armor_id: 30, level: 3},
  {armor_id: 30, level: 4},
  {armor_id: 31, level: 1},
  {armor_id: 31, level: 2},
  {armor_id: 31, level: 3},
  {armor_id: 31, level: 4},
  {armor_id: 32, level: 1},
  {armor_id: 32, level: 2},
  {armor_id: 32, level: 3},
  {armor_id: 32, level: 4},
  {armor_id: 33, level: 1},
  {armor_id: 33, level: 2},
  {armor_id: 33, level: 3},
  {armor_id: 33, level: 4},
  {armor_id: 34, level: 1},
  {armor_id: 34, level: 2},
  {armor_id: 34, level: 3},
  {armor_id: 34, level: 4},
  {armor_id: 35, level: 1},
  {armor_id: 35, level: 2},
  {armor_id: 35, level: 3},
  {armor_id: 35, level: 4},
  {armor_id: 36, level: 1},
  {armor_id: 36, level: 2},
  {armor_id: 36, level: 3},
  {armor_id: 36, level: 4},
  {armor_id: 37, level: 1},
  {armor_id: 37, level: 2},
  {armor_id: 37, level: 3},
  {armor_id: 37, level: 4},
  {armor_id: 38, level: 1},
  {armor_id: 38, level: 2},
  {armor_id: 38, level: 3},
  {armor_id: 38, level: 4},
  {armor_id: 39, level: 1},
  {armor_id: 39, level: 2},
  {armor_id: 39, level: 3},
  {armor_id: 39, level: 4},
  {armor_id: 40, level: 1},
  {armor_id: 40, level: 2},
  {armor_id: 40, level: 3},
  {armor_id: 40, level: 4},
  {armor_id: 41, level: 1},
  {armor_id: 41, level: 2},
  {armor_id: 41, level: 3},
  {armor_id: 41, level: 4},
  {armor_id: 42, level: 1},
  {armor_id: 42, level: 2},
  {armor_id: 42, level: 3},
  {armor_id: 42, level: 4},
  {armor_id: 43, level: 1},
  {armor_id: 43, level: 2},
  {armor_id: 43, level: 3},
  {armor_id: 43, level: 4},
  {armor_id: 44, level: 1},
  {armor_id: 44, level: 2},
  {armor_id: 44, level: 3},
  {armor_id: 44, level: 4},
  {armor_id: 45, level: 1},
  {armor_id: 45, level: 2},
  {armor_id: 45, level: 3},
  {armor_id: 45, level: 4},
  {armor_id: 46, level: 1},
  {armor_id: 46, level: 2},
  {armor_id: 46, level: 3},
  {armor_id: 46, level: 4},
  {armor_id: 9, level: 4}
])
LevelUpItem.create!([
  {level_id: 1, item_id: 1, count: 5},
  {level_id: 1, item_id: 2, count: 5},
  {level_id: 2, item_id: 2, count: 15},
  {level_id: 2, item_id: 3, count: 10},
  {level_id: 3, item_id: 4, count: 15},
  {level_id: 3, item_id: 5, count: 5},
  {level_id: 4, item_id: 6, count: 2},
  {level_id: 4, item_id: 7, count: 1},
  {level_id: 5, item_id: 1, count: 5},
  {level_id: 5, item_id: 2, count: 5},
  {level_id: 6, item_id: 2, count: 15},
  {level_id: 6, item_id: 3, count: 10},
  {level_id: 7, item_id: 4, count: 15},
  {level_id: 7, item_id: 5, count: 5},
  {level_id: 8, item_id: 6, count: 2},
  {level_id: 8, item_id: 7, count: 1},
  {level_id: 9, item_id: 1, count: 5},
  {level_id: 9, item_id: 2, count: 5},
  {level_id: 10, item_id: 2, count: 15},
  {level_id: 10, item_id: 3, count: 10},
  {level_id: 11, item_id: 4, count: 15},
  {level_id: 11, item_id: 5, count: 5},
  {level_id: 12, item_id: 6, count: 2},
  {level_id: 12, item_id: 7, count: 1},
  {level_id: 14, item_id: 8, count: 3},
  {level_id: 14, item_id: 9, count: 2},
  {level_id: 15, item_id: 9, count: 4},
  {level_id: 15, item_id: 10, count: 1},
  {level_id: 16, item_id: 10, count: 2},
  {level_id: 16, item_id: 11, count: 1},
  {level_id: 17, item_id: 8, count: 1},
  {level_id: 18, item_id: 8, count: 3},
  {level_id: 18, item_id: 9, count: 2},
  {level_id: 19, item_id: 9, count: 4},
  {level_id: 19, item_id: 10, count: 1},
  {level_id: 20, item_id: 10, count: 2},
  {level_id: 20, item_id: 11, count: 1},
  {level_id: 21, item_id: 8, count: 1},
  {level_id: 22, item_id: 8, count: 3},
  {level_id: 22, item_id: 9, count: 2},
  {level_id: 23, item_id: 9, count: 4},
  {level_id: 23, item_id: 10, count: 1},
  {level_id: 24, item_id: 10, count: 2},
  {level_id: 24, item_id: 11, count: 1},
  {level_id: 13, item_id: 8, count: 1},
  {level_id: 25, item_id: 12, count: 3},
  {level_id: 25, item_id: 13, count: 3},
  {level_id: 29, item_id: 12, count: 3},
  {level_id: 29, item_id: 13, count: 3},
  {level_id: 33, item_id: 12, count: 3},
  {level_id: 33, item_id: 13, count: 3},
  {level_id: 26, item_id: 14, count: 5},
  {level_id: 26, item_id: 15, count: 5},
  {level_id: 30, item_id: 14, count: 5},
  {level_id: 30, item_id: 15, count: 5},
  {level_id: 34, item_id: 14, count: 5},
  {level_id: 34, item_id: 15, count: 5},
  {level_id: 27, item_id: 16, count: 5},
  {level_id: 27, item_id: 17, count: 10},
  {level_id: 31, item_id: 16, count: 5},
  {level_id: 31, item_id: 17, count: 10},
  {level_id: 35, item_id: 16, count: 5},
  {level_id: 35, item_id: 17, count: 10},
  {level_id: 28, item_id: 18, count: 5},
  {level_id: 28, item_id: 19, count: 15},
  {level_id: 32, item_id: 18, count: 5},
  {level_id: 32, item_id: 19, count: 15},
  {level_id: 160, item_id: 18, count: 5},
  {level_id: 160, item_id: 19, count: 15},
  {level_id: 36, item_id: 20, count: 3},
  {level_id: 44, item_id: 20, count: 3},
  {level_id: 40, item_id: 20, count: 3},
  {level_id: 37, item_id: 20, count: 5},
  {level_id: 37, item_id: 16, count: 3},
  {level_id: 41, item_id: 20, count: 5},
  {level_id: 41, item_id: 16, count: 3},
  {level_id: 45, item_id: 20, count: 5},
  {level_id: 45, item_id: 16, count: 3},
  {level_id: 38, item_id: 16, count: 8},
  {level_id: 38, item_id: 21, count: 3},
  {level_id: 42, item_id: 16, count: 8},
  {level_id: 42, item_id: 21, count: 3},
  {level_id: 46, item_id: 16, count: 8},
  {level_id: 46, item_id: 21, count: 3},
  {level_id: 47, item_id: 21, count: 8},
  {level_id: 47, item_id: 22, count: 5},
  {level_id: 43, item_id: 21, count: 8},
  {level_id: 43, item_id: 22, count: 5},
  {level_id: 39, item_id: 21, count: 8},
  {level_id: 39, item_id: 22, count: 5},
  {level_id: 48, item_id: 23, count: 1},
  {level_id: 48, item_id: 24, count: 2},
  {level_id: 52, item_id: 23, count: 1},
  {level_id: 52, item_id: 24, count: 2},
  {level_id: 56, item_id: 23, count: 1},
  {level_id: 56, item_id: 24, count: 2},
  {level_id: 57, item_id: 23, count: 3},
  {level_id: 57, item_id: 25, count: 4},
  {level_id: 53, item_id: 23, count: 3},
  {level_id: 53, item_id: 25, count: 4},
  {level_id: 49, item_id: 23, count: 3},
  {level_id: 49, item_id: 25, count: 4},
  {level_id: 50, item_id: 26, count: 3},
  {level_id: 50, item_id: 27, count: 3},
  {level_id: 54, item_id: 26, count: 3},
  {level_id: 54, item_id: 27, count: 3},
  {level_id: 58, item_id: 26, count: 3},
  {level_id: 58, item_id: 27, count: 3},
  {level_id: 59, item_id: 26, count: 5},
  {level_id: 59, item_id: 28, count: 2},
  {level_id: 55, item_id: 26, count: 5},
  {level_id: 55, item_id: 28, count: 2},
  {level_id: 51, item_id: 26, count: 5},
  {level_id: 51, item_id: 28, count: 2},
  {level_id: 71, item_id: 31, count: 15},
  {level_id: 71, item_id: 32, count: 15},
  {level_id: 67, item_id: 31, count: 15},
  {level_id: 67, item_id: 32, count: 15},
  {level_id: 63, item_id: 31, count: 15},
  {level_id: 63, item_id: 32, count: 15},
  {level_id: 62, item_id: 30, count: 10},
  {level_id: 62, item_id: 31, count: 5},
  {level_id: 66, item_id: 30, count: 10},
  {level_id: 66, item_id: 31, count: 5},
  {level_id: 70, item_id: 30, count: 10},
  {level_id: 70, item_id: 31, count: 5},
  {level_id: 69, item_id: 29, count: 8},
  {level_id: 69, item_id: 30, count: 5},
  {level_id: 65, item_id: 29, count: 8},
  {level_id: 65, item_id: 30, count: 5},
  {level_id: 61, item_id: 29, count: 8},
  {level_id: 61, item_id: 30, count: 5},
  {level_id: 64, item_id: 29, count: 5},
  {level_id: 68, item_id: 29, count: 5},
  {level_id: 60, item_id: 29, count: 5},
  {level_id: 72, item_id: 33, count: 5},
  {level_id: 72, item_id: 31, count: 3},
  {level_id: 80, item_id: 33, count: 5},
  {level_id: 80, item_id: 31, count: 3},
  {level_id: 76, item_id: 33, count: 5},
  {level_id: 76, item_id: 31, count: 3},
  {level_id: 83, item_id: 33, count: 20},
  {level_id: 83, item_id: 10, count: 1},
  {level_id: 79, item_id: 33, count: 20},
  {level_id: 79, item_id: 10, count: 1},
  {level_id: 75, item_id: 33, count: 20},
  {level_id: 75, item_id: 10, count: 1},
  {level_id: 74, item_id: 33, count: 10},
  {level_id: 74, item_id: 34, count: 2},
  {level_id: 78, item_id: 33, count: 10},
  {level_id: 78, item_id: 34, count: 2},
  {level_id: 82, item_id: 33, count: 10},
  {level_id: 82, item_id: 34, count: 2},
  {level_id: 81, item_id: 33, count: 8},
  {level_id: 81, item_id: 27, count: 3},
  {level_id: 77, item_id: 33, count: 8},
  {level_id: 77, item_id: 27, count: 3},
  {level_id: 73, item_id: 33, count: 8},
  {level_id: 73, item_id: 27, count: 3},
  {level_id: 95, item_id: 44, count: 10},
  {level_id: 95, item_id: 45, count: 5},
  {level_id: 91, item_id: 44, count: 10},
  {level_id: 91, item_id: 45, count: 5},
  {level_id: 87, item_id: 44, count: 10},
  {level_id: 87, item_id: 45, count: 5},
  {level_id: 86, item_id: 42, count: 8},
  {level_id: 86, item_id: 43, count: 5},
  {level_id: 90, item_id: 42, count: 8},
  {level_id: 90, item_id: 43, count: 5},
  {level_id: 94, item_id: 42, count: 8},
  {level_id: 94, item_id: 43, count: 5},
  {level_id: 93, item_id: 40, count: 5},
  {level_id: 93, item_id: 41, count: 5},
  {level_id: 89, item_id: 40, count: 5},
  {level_id: 89, item_id: 41, count: 5},
  {level_id: 85, item_id: 40, count: 5},
  {level_id: 85, item_id: 41, count: 5},
  {level_id: 84, item_id: 40, count: 3},
  {level_id: 88, item_id: 40, count: 3},
  {level_id: 92, item_id: 40, count: 3},
  {level_id: 107, item_id: 49, count: 10},
  {level_id: 107, item_id: 50, count: 5},
  {level_id: 103, item_id: 49, count: 10},
  {level_id: 103, item_id: 50, count: 5},
  {level_id: 99, item_id: 49, count: 10},
  {level_id: 99, item_id: 50, count: 5},
  {level_id: 98, item_id: 18, count: 8},
  {level_id: 98, item_id: 48, count: 5},
  {level_id: 102, item_id: 18, count: 8},
  {level_id: 102, item_id: 48, count: 5},
  {level_id: 106, item_id: 18, count: 8},
  {level_id: 106, item_id: 48, count: 5},
  {level_id: 105, item_id: 46, count: 5},
  {level_id: 105, item_id: 47, count: 3},
  {level_id: 101, item_id: 46, count: 5},
  {level_id: 101, item_id: 47, count: 3},
  {level_id: 97, item_id: 46, count: 5},
  {level_id: 97, item_id: 47, count: 3},
  {level_id: 96, item_id: 46, count: 3},
  {level_id: 100, item_id: 46, count: 3},
  {level_id: 104, item_id: 46, count: 3},
  {level_id: 119, item_id: 9, count: 2},
  {level_id: 119, item_id: 10, count: 2},
  {level_id: 115, item_id: 9, count: 2},
  {level_id: 115, item_id: 10, count: 2},
  {level_id: 111, item_id: 9, count: 2},
  {level_id: 111, item_id: 10, count: 2},
  {level_id: 110, item_id: 53, count: 2},
  {level_id: 110, item_id: 28, count: 2},
  {level_id: 114, item_id: 53, count: 2},
  {level_id: 114, item_id: 28, count: 2},
  {level_id: 118, item_id: 53, count: 2},
  {level_id: 118, item_id: 28, count: 2},
  {level_id: 117, item_id: 52, count: 3},
  {level_id: 117, item_id: 27, count: 3},
  {level_id: 113, item_id: 52, count: 3},
  {level_id: 113, item_id: 27, count: 3},
  {level_id: 109, item_id: 52, count: 3},
  {level_id: 109, item_id: 27, count: 3},
  {level_id: 108, item_id: 51, count: 5},
  {level_id: 108, item_id: 31, count: 3},
  {level_id: 112, item_id: 51, count: 5},
  {level_id: 112, item_id: 31, count: 3},
  {level_id: 116, item_id: 51, count: 5},
  {level_id: 116, item_id: 31, count: 3},
  {level_id: 131, item_id: 53, count: 10},
  {level_id: 131, item_id: 58, count: 15},
  {level_id: 127, item_id: 53, count: 10},
  {level_id: 127, item_id: 58, count: 15},
  {level_id: 123, item_id: 53, count: 10},
  {level_id: 123, item_id: 58, count: 15},
  {level_id: 122, item_id: 53, count: 5},
  {level_id: 122, item_id: 57, count: 5},
  {level_id: 126, item_id: 53, count: 5},
  {level_id: 126, item_id: 57, count: 5},
  {level_id: 130, item_id: 53, count: 5},
  {level_id: 130, item_id: 57, count: 5},
  {level_id: 129, item_id: 55, count: 5},
  {level_id: 129, item_id: 56, count: 5},
  {level_id: 125, item_id: 55, count: 5},
  {level_id: 125, item_id: 56, count: 5},
  {level_id: 121, item_id: 55, count: 5},
  {level_id: 121, item_id: 56, count: 5},
  {level_id: 120, item_id: 54, count: 3},
  {level_id: 124, item_id: 54, count: 3},
  {level_id: 128, item_id: 54, count: 3},
  {level_id: 143, item_id: 7, count: 1},
  {level_id: 143, item_id: 62, count: 2},
  {level_id: 139, item_id: 7, count: 1},
  {level_id: 139, item_id: 63, count: 2},
  {level_id: 135, item_id: 7, count: 1},
  {level_id: 135, item_id: 62, count: 2},
  {level_id: 134, item_id: 61, count: 5},
  {level_id: 134, item_id: 69, count: 2},
  {level_id: 138, item_id: 61, count: 5},
  {level_id: 138, item_id: 72, count: 2},
  {level_id: 142, item_id: 61, count: 5},
  {level_id: 142, item_id: 66, count: 2},
  {level_id: 141, item_id: 60, count: 5},
  {level_id: 141, item_id: 65, count: 2},
  {level_id: 137, item_id: 60, count: 5},
  {level_id: 137, item_id: 71, count: 2},
  {level_id: 133, item_id: 60, count: 5},
  {level_id: 133, item_id: 68, count: 2},
  {level_id: 132, item_id: 59, count: 10},
  {level_id: 132, item_id: 67, count: 2},
  {level_id: 136, item_id: 59, count: 10},
  {level_id: 136, item_id: 70, count: 2},
  {level_id: 140, item_id: 59, count: 10},
  {level_id: 140, item_id: 64, count: 2},
  {level_id: 144, item_id: 45, count: 3},
  {level_id: 145, item_id: 45, count: 3},
  {level_id: 145, item_id: 62, count: 2},
  {level_id: 146, item_id: 45, count: 3},
  {level_id: 146, item_id: 63, count: 2},
  {level_id: 147, item_id: 45, count: 10},
  {level_id: 147, item_id: 11, count: 2},
  {level_id: 151, item_id: 38, count: 10},
  {level_id: 151, item_id: 39, count: 10},
  {level_id: 150, item_id: 37, count: 5},
  {level_id: 150, item_id: 38, count: 5},
  {level_id: 149, item_id: 35, count: 5},
  {level_id: 149, item_id: 36, count: 5},
  {level_id: 148, item_id: 35, count: 3},
  {level_id: 159, item_id: 38, count: 10},
  {level_id: 159, item_id: 39, count: 10},
  {level_id: 155, item_id: 38, count: 10},
  {level_id: 155, item_id: 39, count: 10},
  {level_id: 158, item_id: 37, count: 5},
  {level_id: 158, item_id: 38, count: 5},
  {level_id: 154, item_id: 37, count: 5},
  {level_id: 154, item_id: 38, count: 5},
  {level_id: 153, item_id: 35, count: 5},
  {level_id: 153, item_id: 36, count: 5},
  {level_id: 157, item_id: 35, count: 5},
  {level_id: 157, item_id: 36, count: 5},
  {level_id: 156, item_id: 35, count: 3},
  {level_id: 152, item_id: 35, count: 3}
])
Player.create!([
  {name: "Link"}
])
